# Generated by Django 3.2.4 on 2022-10-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('namedate_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
                ('tempmax', models.FloatField()),
                ('tempmin', models.FloatField()),
                ('temp', models.FloatField()),
                ('feelslikemax', models.FloatField()),
                ('feelslikemin', models.FloatField()),
                ('feelslike', models.FloatField()),
                ('dew', models.FloatField()),
                ('humidity', models.FloatField()),
                ('precip', models.FloatField()),
                ('precipprob', models.IntegerField()),
                ('precipcover', models.FloatField()),
                ('preciptype', models.CharField(max_length=255)),
                ('snow', models.FloatField()),
                ('snowdepth', models.FloatField()),
                ('windgust', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('winddir', models.FloatField()),
                ('sealevelpressure', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('visibility', models.FloatField()),
                ('solarradiation', models.FloatField()),
                ('solarenergy', models.FloatField()),
                ('uvindex', models.IntegerField()),
                ('severerisk', models.CharField(max_length=255)),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('moonphase', models.FloatField()),
                ('conditions', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('stations', models.CharField(max_length=255)),
            ],
        ),
    ]
